name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publishing package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setting up NODE
        uses: actions/setup-node@v1
        with:
          node-version: 16.10.0
          registry-url: 'https://npm.pkg.github.com'
          scope: '@schmolie'

      - name: Installing dependencies
        run: npm ci

      - name: Publishing
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
